#pragma once

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#define VIAL_KEYBOARD_UID {0x9C, 0xA5, 0x86, 0x46, 0x6D, 0x0D, 0x8D, 0x01}
#define VIAL_UNLOCK_COMBO_ROWS {0, 3}
#define VIAL_UNLOCK_COMBO_COLS {0, 13}

#define VIAL_KEY_OVERRIDE_ENTRIES 4
